apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaguar-udf
  namespace: iris-vdap-cicd
  labels:
    app: jaguar-udf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaguar-udf
  template:
    metadata:
      name: jaguar-udf
      labels:
        app: jaguar-udf
    spec:
      containers:
        - name: jaguar-udf
          image: repo.iris.tools/irisdev/jaguar_udf:dev
          imagePullPolicy: IfNotPresent
