apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaguar-udf
  namespace: iris-vdap-cicd
  labels:
    app: jaguar-udf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaguar-udf
  template:
    metadata:
      name: jaguar-udf
      labels:
        app: jaguar-udf
    spec:
      containers:
        - name: jaguar-udf
          image: repo.iris.tools/iris/jaguar_udf:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /mount
              name: extvolume
            - mountPath: /app/src/nginx.conf
              subPath: nginx.conf
              name: jaguar-udf-cm
            - mountPath: /app/src/vue.config.js
              subPath: vue.config.js
              name: jaguar-udf-cm
      volumes:
        - name: extvolume
          persistentVolumeClaim:
            claimName: pvc-iris
        - name: jaguar-udf-cm
          configMap:
            name: jaguar-udf-cm
