apiVersion: v1
kind: Service
metadata:
  name: jaguar-udf
  namespace: iris-vdap-cicd
spec:
  selector:
    app: jaguar-udf
  ports:
    - name: nginx-port
      nodePort: 36088
      port: 8080
      protocol: TCP
      targetPort: nginx-port
  type: NodePort